#!/usr/bin/env sh
HOOKS_DIR=".githooks"
GIT_HOOKS_DIR=".git/hooks"

if [ ! -d "$HOOKS_DIR" ]; then
  echo "Error: Directory $HOOKS_DIR not found."
  exit 1
fi

if [ ! -d "$GIT_HOOKS_DIR" ]; then
  echo "Error: Directory $GIT_HOOKS_DIR not found."
  exit 1
fi

for hook in "$HOOKS_DIR"/*; do
  if [ "$(basename "$hook")" != "install" ]; then
    cp "$hook" "$GIT_HOOKS_DIR/"
    chmod +x "$GIT_HOOKS_DIR/$(basename "$hook")"
    echo "Hook $(basename "$hook") installed."
  fi
done

echo "Hooks installed successfully."
